# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.cache/wt [current_project]
set_property parent.project_path D:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  d:/NextLab/Vivado/OPLL_ADC/ip_repo/AXIS_Test_1.0
  d:/NextLab/Vivado/OPLL_ADC/ip_repo/PMOD_AD1_Driver_1.0
  d:/NextLab/Vivado/OPLL_ADC/ip_repo/PMOD_AD1_Driver_1.0
  d:/NextLab/Vivado/OPLL_ADC/ip_repo/PMOD_AD1_Driver_1.0
} [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib D:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/hdl/DMA_design_wrapper.v
add_files D:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/DMA_design.bd
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_processing_system7_0_0/DMA_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_dma_0_0/DMA_design_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_dma_0_0/DMA_design_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_dma_0_0/DMA_design_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_10/bd_0ee2_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_17/bd_0ee2_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_20/bd_0ee2_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_21/bd_0ee2_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_22/bd_0ee2_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_23/bd_0ee2_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_24/bd_0ee2_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_25/bd_0ee2_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_18/bd_0ee2_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_19/bd_0ee2_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_11/bd_0ee2_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_12/bd_0ee2_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_13/bd_0ee2_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_2/bd_0ee2_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_3/bd_0ee2_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_4/bd_0ee2_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_5/bd_0ee2_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_6/bd_0ee2_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_1/bd_0ee2_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/bd_0/ip/ip_1/bd_0ee2_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_rst_ps7_0_100M_0/DMA_design_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_rst_ps7_0_100M_0/DMA_design_rst_ps7_0_100M_0.xdc]
set_property used_in_synthesis false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_ila_0_1/DMA_design_ila_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_gpio_0_0/DMA_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_gpio_0_0/DMA_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_axi_gpio_0_0/DMA_design_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/ip/DMA_design_auto_pc_0/DMA_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/sources_1/bd/DMA_design/DMA_design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/constrs_1/new/pin_locking.xdc
set_property used_in_implementation false [get_files D:/NextLab/Vivado/OPLL_ADC/OPLL_ADC/OPLL_ADC.srcs/constrs_1/new/pin_locking.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top DMA_design_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DMA_design_wrapper.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file DMA_design_wrapper_utilization_synth.rpt -pb DMA_design_wrapper_utilization_synth.pb"
