# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_locking.xdc

# Block Designs: bd/DMA_design/DMA_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design || ORIG_REF_NAME==DMA_design} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_processing_system7_0_0/DMA_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_processing_system7_0_0 || ORIG_REF_NAME==DMA_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_axi_dma_0_0/DMA_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_axi_dma_0_0 || ORIG_REF_NAME==DMA_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_axi_smc_0/DMA_design_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_axi_smc_0 || ORIG_REF_NAME==DMA_design_axi_smc_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_rst_ps7_0_100M_0/DMA_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==DMA_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_ps7_0_axi_periph_0/DMA_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==DMA_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_xlconstant_0_0/DMA_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_xlconstant_0_0 || ORIG_REF_NAME==DMA_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_ila_0_1/DMA_design_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_ila_0_1 || ORIG_REF_NAME==DMA_design_ila_0_1} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_xbar_0/DMA_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_xbar_0 || ORIG_REF_NAME==DMA_design_xbar_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_PMOD_AD1_Driver_0_0/DMA_design_PMOD_AD1_Driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_PMOD_AD1_Driver_0_0 || ORIG_REF_NAME==DMA_design_PMOD_AD1_Driver_0_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_axi_gpio_0_0/DMA_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_axi_gpio_0_0 || ORIG_REF_NAME==DMA_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_xlconcat_0_0/DMA_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_xlconcat_0_0 || ORIG_REF_NAME==DMA_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_xlconstant_1_0/DMA_design_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_xlconstant_1_0 || ORIG_REF_NAME==DMA_design_xlconstant_1_0} -quiet] -quiet

# IP: bd/DMA_design/ip/DMA_design_auto_pc_0/DMA_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_design_auto_pc_0 || ORIG_REF_NAME==DMA_design_auto_pc_0} -quiet] -quiet

# XDC: bd/DMA_design/DMA_design_ooc.xdc
