webtalk_init -webtalk_dir D:\\NextLab\\Vivado\\OPLL_ADC\\OPLL_ADC\\OPLL_ADC.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-03-19 15:58:56" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "88bbpcldlpnakljgpa3hga3krr" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_33" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "33" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.047 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1521480467855" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key hwid -value "1520274515792" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key bspid -value "1520274594968" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key projSize -value "213.40234375" -context "sdk\\\\application/1521480467855"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1521489536138"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1521489536138"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1521489536138"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1521489536138"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1521489536138"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1521489536138"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1521489536138"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1521489536138"
webtalk_transmit -clientid 2550645783 -regid "" -xml D:\\NextLab\\Vivado\\OPLL_ADC\\OPLL_ADC\\OPLL_ADC.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\NextLab\\Vivado\\OPLL_ADC\\OPLL_ADC\\OPLL_ADC.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\NextLab\\Vivado\\OPLL_ADC\\OPLL_ADC\\OPLL_ADC.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
